rule all:
    input:
        "results/comparison.csv"

rule create_db:
    input:
        "input/create_and_load_db.sql"
    output:
        "inspections.db"
    shell:
        """
        sqlite3 {output} < {input}
        """

rule aggregate_sql:
    input:
        "inspections.db",
        "aggregate.sql"
    output:
        "results/sql-fac-types.csv"
    shell:
        """
        sqlite3 {input[0]} < {input[1]}
        """

rule aggregate_pandas:
    input:
        "input/Food_Inspections_50k.csv"
    output:
        "results/pandas-fac-types.csv"
    shell:
        """
        python aggregate.py
        """

rule compare:
    input:
        "results/sql-fac-types.csv",
        "results/pandas-fac-types.csv"
    output:
        "results/comparison.csv"
    shell:
        """
        python compare.py
        """
